### ISSUE TITLE
Is it possible to use lenses with different focal lengths 

### ISSUE THREAD

**Issue by SaajHosseini** [ricktu288/ray-optics#110]
Hello,

I am new to the GitHub, so I hope I am putting my question in a right spot. 

From my recent approaches to the software I understood I can easily use typical concave and convex lenses. However, I was wondering if it be possible to have an Ideal leans with different focal points such as plano-concave lens etc. Or if it be possible to import the geometry of lens as an .stl file to the simulation. 

Regards,

**Comment by ricktu288** [comment]
The "ideal lens" tool is an ideal object that obeys the thin lens equation exactly, so it does not corresponds to a specific shape, and whether it is plano-concave or double concave is irrelevant.

If you want to create a plano-concave lens where the concave surface is spherical (circular), you can use the "spherical lens" tool with a grid and adjust the points:
![圖片](https://github.com/ricktu288/ray-optics/assets/1409171/8f46472a-cab0-498b-a099-1eba44022df5)
Or you can use the "Custom shape" tool.

This is a 2D optics simulator, so a 3d .stl file is irrelevant to the goal of this simulator. Importing 2d CAD file is desirable but not currently possible. However, you may model the curve with a mathematical equation and use the "Custom equation" tool.

**Comment by SaajHosseini** [comment]
Thank you so much for your response.
