### ISSUE TITLE
page stuck on processing...

### ISSUE THREAD

**Issue by dimiphoton** [ricktu288/ray-optics#112]
(firefox - ubuntu)
Hello, I can't draw or load a model, the webpage is stuck on the black screen with "Welcome to Ray Optics Simulation"

on the bottom left, it is written:

processing, click to stop

**Comment by ricktu288** [comment]
Can you give me a screenshot and possibly developer console output?

**Comment by dimiphoton** [comment]
thanks for the answer.
the developper console output is:
WEBGL_debug_renderer_info is deprecated in Firefox and will be removed. Please use RENDERER.  

SecurityError: Permission denied to access property "document" on cross-origin object [content-script.js:504](moz-extension://a369c5de-8a14-45ae-b27e-5b199ed9e7b6/content-script.js "View source in Debugger → moz-extension://a369c5de-8a14-45ae-b27e-5b199ed9e7b6/content-script.js:504")  

WEBGL_debug_renderer_info is deprecated in Firefox and will be removed. Please use RENDERER.  

SecurityError: Permission denied to access property "document" on cross-origin object [content-script.js:504](moz-extension://a369c5de-8a14-45ae-b27e-5b199ed9e7b6/content-script.js "View source in Debugger → moz-extension://a369c5de-8a14-45ae-b27e-5b199ed9e7b6/content-script.js:504")  

Source map error: Error: request failed with status 404 Resource URL: [https://phydemo.app/ray-optics/thirdparty/bootstrap-4.1.1/bootstrap.min.css](https://phydemo.app/ray-optics/thirdparty/bootstrap-4.1.1/bootstrap.min.css "https://phydemo.app/ray-optics/thirdparty/bootstrap-4.1.1/bootstrap.min.css") Source Map URL: bootstrap.min.css.map

**Comment by ricktu288** [comment]
My system is also Firefox on Ubuntu but there is no problem.

This app does not use WebGL and in particular there is nowhere in the code that can generate WEBGL_debug_renderer_info warning. Moreover, there is no script named content-script.js that can generate the cross-origin error.

It is likely that this error is due to an extension installed on your Firefox.
