### ISSUE TITLE
Grid rendering is extremely slow

### ISSUE THREAD

**Issue by Kamilkampfwagen-II** [ricktu288/ray-optics#113]
Enabling the background grid tanks performance and often causes inresposiveness especially at higher field of view.
I have exact issue on both Librewolf (Firefox fork) and Ungoogled Chromium.

**Comment by ricktu288** [comment]
Can you give an example screen recording?

**Comment by Kamilkampfwagen-II** [comment]
> Can you give an example screen recording?

Sure, I noticed that only 2-3 cpu threads spike during this. I have webgl enabled (it's disabled in Librewolf by default)

https://github.com/ricktu288/ray-optics/assets/84380947/7f528b9e-8657-4a81-8f51-2f7286799703

Here are my webgl related settings in Librewolf:
![image](https://github.com/ricktu288/ray-optics/assets/84380947/57c87746-280c-45d8-99b6-2cfb1549860c)

**Comment by ricktu288** [comment]
Now in the new version, the grid will only be redrawn when the user move/resize the view.
