### ISSUE TITLE
Gain medium

### ISSUE THREAD

**Issue by jacione** [ricktu288/ray-optics#116]
I would love to see an optical gain medium implemented. I could see it going in either the "Glass" or "Light Source" menus.

For context, the primary application I would use this feature for is to simulate a laser cavity: concave mirror on one end, flat beamsplitter (T<0.05) on the other, gain medium in the middle, and a tiny light source to start the process.

The functionality of it might be tricky to get right. My first approach would be to just have it increase the intensity of every ray that goes through it, with an exponential dependence on the path length through the medium. However, doing something like that could easily lead to overflow errors if a ray makes too many passes through the medium (e.g. in some kind of cavity).

In a real gain medium, the gain is limited by the rate at which atoms can be excited. I think perhaps a good way to simulate this would be to have it so that the amount of gain (coefficient per unit path length) has some kind of sigmoid relationship with intensity. More specifically, you might say that, when going from one point to the next through the medium, the intensity is multiplied by some coefficient
k = 1 + G / (1+(x/xs))
where G is called the small-signal gain, x is the current intensity, and xs is the saturation intensity. The G and xs parameters would probably need to be connected to sliders.

If you're feeling very ambitious, you could also add a frequency-dependent factor, which would change the gain coefficient to
k = 1 + G / (1+ ((f-f0)^2/df^2) + (x/xs))
where f is the frequency of the ray, f0 is the transition frequency of the gain medium (basically the frequency that the laser wants to lase) and df is an acceptable bandwidth range. With something like that, you could seed a laser cavity with white light, then show that the light that escapes is limited to the bandwidth of the gain medium.

**Comment by ricktu288** [comment]
For your laser cavity application, it seems that a simple linear shape object is enough (without the need to simulate how the ray decays within the medium stepwise).

On the other hand, if a finite-area object should be used, then I think the approach would be similar to #109.

**Comment by ricktu288** [comment]
The intensity-dependent gain is not easy to implement. Note that the "brightness" property of a ray object in this simulator is not directly the intensity. To get the intensity of a beam, we need to catch at least two non-gap rays and divide their average "brightness" by their spatial separation, which in the current simulator requires temporarily storing some ray information in the object (as is currently done for the "detector" tool), which complicates things a lot.

**Comment by ricktu288** [comment]
I think nonlinear optics is almost impossible with the ray tracing algorithm currently used in this simulator.

**Comment by ricktu288** [comment]
For constant gain, there is a hacky way to achieve it in the current simulator. Just let the ray pass through a 45 degree beam splitter, and set the transmission ratio of the beam splitter to a value larger than 1 (by editing the number in the text box).

**Comment by jacione** [comment]
That's ok, it was admittedly a big ask. Thanks for looking into it!

I did manage to modify your example into a [stable laser cavity](https://phydemo.app/ray-optics/simulator/#XQAAAAIIAwAAAAAAAABFKcrGU8hqLFnplfssnTFrVrEZ-XiP9Y348FrinKNdt-77GpNkdE0ksTCG7Evckp6OqXLgSB1d8KWiSktx0PCMqIng-ZvVNOzdSt-dupQasgIseV7L0Qz3cjjY8jUV2JLLu4lYYjxNJrUVzVTQeOG5EQDlt9g9R4Dof6SJ79YHwKRVSkLiX5mcNSDrl9v_dk4km4WmvD_Lkw16-7u2yVlJuK79CXFwBkAF7_tBq0kh-e5bsN9mINzaDbxcjEDncW3qb94vo-6isBGGa20-RNu_lq6OYGfZ79XQMwCSwI2MqYP8muOTb-xg35pLThftmksj8cS3ojZpvhA3CWX14WlrdyDcdx0KMD1uEuWD2O16qw4hPadXHW5d_KSP3eWID9ytk0hmSsljpEphBE3HxjA5Runz8je04ex-iGDP5caJy7Msn3drWW6Kptbe9_v3pCBDoyDEFI8J__SJOwktZSI2_GbYclRxrZre4PdG5SPv9TTSBCgJ7Y8xQFgplB1Vv965V1MR9MNcSus5FQBPL3__vaMQ6g). The initial light source is a single ray at 0.01 brightness with 1% output coupling, and the result is basically a near-infinitely bright beam. Still a really cool demo, which I will probably show my research group, so thanks for making a great tool :)
