### ISSUE TITLE
Hyperbolic functions not working

### ISSUE THREAD

**Issue by jefffhaynes** [ricktu288/ray-optics#120]
First off, awesome simulator.  Total novice here but it's been super helpful to visualize some things.  

Sorry if I'm missing something, but is it possible to enter hyperbolic functions (e.g. tanh) in the function editor?  It seems to grab the ```tan``` part and not want to hang out for the ```h```.

**Comment by ricktu288** [comment]
I've added the hyperbolic functions and it works fine for the tools that use Evaluatex (custom equation mirror and glass). However, for the tools that use Math.js (gradient-index glasses), tanh does not seems to work (even if sinh and cosh work).

**Comment by ricktu288** [comment]
Still some weird bugs possibly from Evaluatex. For example, x*sinh(x) does not work.
