### ISSUE TITLE
Feature request: Diffraction gratings

### ISSUE THREAD

**Issue by wangnick** [ricktu288/ray-optics#121]
It would be awesome to have diffraction gratings added as a tool option. I'm currently building a simple spectrometer, and such tool would much help its simulation and design.

**Comment by gljames24** [comment]
I was just thinking about this as I'm currently trying to model a monochromometer. I'd be willing to work on this.

**Comment by gljames24** [comment]
They would probably be easiest to implement as a mirror segment object for the reflected rays and just have the rays be set to the angle and brightness of their m value until the brigtness is zero or possibly be a slider number. There will definitely need to be a slider for the lines/mm as well. I'm not sure where transpent gratings would go. Possibly under blockers, but maybe just as a toggle.

**Comment by ricktu288** [comment]
Maybe a single tool under "others"?

**Comment by gljames24** [comment]
Yeah, I could do that. I'll try to get it in a workable state this weekend.
