### ISSUE TITLE
Scripting?

### ISSUE THREAD

**Issue by jumpjack** [ricktu288/ray-optics#125]
Is it possible to script objects?
I need to simulate a rotating and translating source of lilght.

**Comment by ricktu288** [comment]
A desmos-like variable/equation system has been proposed. See the discussion in #105.

In the current simulator, you may try to use the JavaScript console to access the global `objs` array. Call `draw()` to redraw the scene.

**Comment by jumpjack** [comment]
it's amazing that this tools expose so many functions, but what about grouping them under one single collector, such as rayOptics, so developer can have a total list of them at a glance? rayOptics.add(), rayOptics.objs, ...

What I really like is that it works also locally and out of the box, please don't change this! :-)
