### ISSUE TITLE
Is it possible to draw a parabolic reflective surface?

### ISSUE THREAD

**Issue by gsportelli** [ricktu288/ray-optics#13]
Amazing work, thank you!

As in the subject, is it possible to draw a parabolic reflective surface by e.g. specifying focus and directrix?

**Comment by j3soon** [comment]
This project doesn't support parabolic reflective surface. But you can use the `Glass (Other shapes)` tool to create almost any shape you want.

**Comment by baryluk** [comment]
> This project doesn't support parabolic reflective surface. But you can use the `Glass (Other shapes)` tool to create almost any shape you want.

That is for lenses. The question is about the reflectors / mirrors. There is no way to do that right now other than manually approximating by houndreths of line segments, which can't be done properly by hand accurately, plus once you create it and want to change it, everything needs to be done from scratch.

It should be possible to create an arc of a parabola (and other functions, even maybe allow freeform function formula for it), and minimum / maximum so you can also make off axis / offset parabolas, which are very useful in practice.

**Comment by ricktu288** [comment]
Implemented by @pfalstad.
