### ISSUE TITLE
Rays count bug?

### ISSUE THREAD

**Issue by jumpjack** [ricktu288/ray-optics#149]
Any idea about why in two identical configurations the rays count changes in this weird way?

First case: 32 rays in central variant, 20 rays in right variant:

![image](https://github.com/ricktu288/ray-optics/assets/1620953/bbbd4ba1-e09f-4e7c-916a-bdfe4b6c6f63)

Second case: 32 rays in central variant, **37** rays in right variant

![image](https://github.com/ricktu288/ray-optics/assets/1620953/48564f3a-0e9c-4098-93d5-99ea3b8bb321)

I'd assume the central/right ratio should remain constant while chaging rays density, but it does not happen.

Try it [here](https://phydemo.app/ray-optics/simulator/#XQAAAAK7CAAAAAAAAABDKcrGU8hqLFnpmU9EnTFrXtfVT8bZE8XK1aL-VxfAXu7Qd-aGpdITjmLt98azixf6MnQiWQCQByQjBD4Lrms5gN7pNhaWS_xe4u6dTbbik5-nz2ozkC9R17zlalpiLTYwChJmCBxsfAOrV8yzs9lMGvhDEE5MhlQiuIb_RFKDdMDqHh5OigxvUBApv4Vs9-e5Mz26wkZyKBY4cwb9XI1co1WwcMnu-vwNIUSnvBUcD7usCt1uFZmUYjZftioruaWwe9AEyC6INKOMkYWJyJdus5IKf_i6-NmW_on0FLiv5BVWoTLvJVNR7XgdCu9R6gHV5w46O6iwlgXImHTjDwGb01vaniWeuRJMMI3fS8-sawRbLXE5sdR3AIIDH7-GhlsuoASuwt5P_9qiO_O1R7sXRuS0uhOxZ8IJI5LN4cVYjFZz-JQdMRM8UzMDw4pwCJ002sw4Zf1ZXkJj-bDuOehUN6ePZfit_Ul1brwAfsEi6lCfjkar1PgJVwnEWh0DfmVu9fXudVSrPCUJpc_TUaxdjIkKITMXvjz0P7m7Sw8umg2Ew3CdQZNTewDL7XOhjrGEBqccQv9uDZMvd93JskPIZi-QhvadAFUBy4i5l_FkvbTmBYGMc1H436g7DMXhzJwPtJ4TwYHzPTyD0PyGlw1W0NeOs-zfmjhN_lezXMWs5UDi8NJGS7K9SOWwP9vrM6BNrmGIm6DhGBeptv5DOWgBo5mmfEbO3o7i3AOWsnfDBSIurOQZIoHP8k5WzcJMZ7kKV-DhsQph17Qfil-0s0WyTsxuAL9ylX7tOzPHr42ywwN2O0FJDwRE6BHTcM-AkfGBc6oQrHjiJR3P5_nCxWRtkmZZgDl8Ac15xu8Ni74up7BERx_WCCGyToKifWc5IWGeCTDUC5tLj2qawzEDHeXsofmkkaqueoS8F6XIA-Gxx3lPfxZbdxAYcQpPwJhLCIaHemDK9R_KtCjDuceF-adUnBVu52PX3a7_PKyNCitjp6jLVlXga-Ai2vhUCoOm8ADgB0t3IEeoCf-6YHrY)

**Comment by ricktu288** [comment]
The power of individual rays saturates to a constant value when "ray density" is too low.

There is a note in the "brightness" property of light sources that this property only works when "ray density" is high enough. Maybe I will add another warning when using the "detector" tool.

**Comment by jumpjack** [comment]
So the right result is the lower image?

**Comment by ricktu288** [comment]
Yes

**Comment by jumpjack** [comment]
> Yes

I would had assumed the opposite: in the rightmost case, the rays are spread more, so I would expect less rays hitting the sensor.

**Comment by ricktu288** [comment]
But you also set yhe brightness of the source on the right to a higher value.

**Comment by jumpjack** [comment]
> But you also set yhe brightness of the source on the right to a higher value.

Damn, this was completely unintentional!

So these are the right screenshots:

![image](https://github.com/user-attachments/assets/9da072e4-83c3-4c05-9dea-ee7cc7d24cda)

![image](https://github.com/user-attachments/assets/0b6f7d95-ee28-4d67-9b03-ecf22428b92e)

But I can't know if this time the results are quite identical (as they were supposed to be)  because of your changes to the code or because of my fixing of the parameters..

**Comment by ricktu288** [comment]
My change of code didn't affect the numbers, and only to show a warning if the ratio will change with ray density.
