### ISSUE TITLE
Sample files

### ISSUE THREAD

**Issue by bembo70** [ricktu288/ray-optics#15]
Anywhere to upload or download user-created files?

**Comment by j3soon** [comment]
Do you mean saving the objects you created? You can click "save" in the toolbar, and then type your preferred file name, your browser should pop out a saving dialog. When you want to restore your creation, click "open" and select the `json` file to load your save.

**Comment by j3soon** [comment]
I've just uploaded some sample files [here](https://github.com/ricktu288/ray-optics/tree/master/samples), you can open the sample files to see the results.
