### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by soamaven** [ricktu288/ray-optics#16]
Hi, I'd like to cite this work and am curious if you have any preference as to how. Thanks.

**Comment by ricktu288** [comment]
You can just cite it using the usual way, with the following information
Author: Yi-Ting Tu
Year: 2016

**Comment by purduephotog** [comment]
Do you have a preferred way of linking to you? This GitHub site or a linkedin profile or ?

**Comment by ricktu288** [comment]
My github profile is fine.
