### ISSUE TITLE
Surface Roughness

### ISSUE THREAD

**Issue by purduephotog** [ricktu288/ray-optics#17]
I'm really full of awe of this application. I put together a quick demonstration in 30 minutes of 3 different theories and sent them off which would have otherwise taken me ... I'm not even sure at this point.

Is there a way to simulate surface roughness or anything less than perfect reflectance? Surface roughness?

I'm trying to create JSON files directly to make my editing better, but it makes it harder to work if I make a jaggy (Triangle or Sawtooth) mirror surface :)

**Comment by ricktu288** [comment]
Now it can be created with Mirror -> Custom equation.
![image](https://user-images.githubusercontent.com/1409171/200151800-b614bed4-268c-4a43-8cf1-41ee6ca8a298.png)
