### ISSUE TITLE
Gaussian beam as a source

### ISSUE THREAD

**Issue by vlaphy** [ricktu288/ray-optics#18]
Thank you for this great simulator!

Are there any plans of adding a Gaussian beam as a source? I am working with lasers and they all have Gaussian profile, so it would be nice for me to see how they interact with lenses in the simulator.

Sincerely,
valphy

**Comment by ricktu288** [comment]
I think Gaussian beams cannot be well described by ray optics. Wave optics is not the purpose of this project.

**Comment by vlaphy** [comment]
Dear Yi-Ting Tu,

I used your Ray Optics Simulation web app to draw one figure for my
scientific paper. To credit you as an author of the simulator I will put
the link to the simulator to the reference list of the paper. Is that ok?

Sincerely yours,
Vlatko Gasparic
