### ISSUE TITLE
Irradiance Map?

### ISSUE THREAD

**Issue by joedg** [ricktu288/ray-optics#19]
Awesome project!  Thanks for making such an useful and easy to use tool! 

One thing that would make it even more useful is to include the irradiance on a surface.  I.e. show a plot of the ray density on a selected surface.  Alternately, you could add another linear element called "detector" that does not modify rays, it just provides a plot of the ray density through the line.   This would make your project an amazing design tool for lighting applications.

**Comment by ricktu288** [comment]
There is a branch of this repo named power-measurement which provide such a tool.
However, there will be a large amount of error when working with Glass objects with a lot of reflections.

**Comment by risoul** [comment]
Really interesting! thanks for this code.

Something that would be great : moving source on a path and draw simultaneously the power on the detector could make an excellent solar panel configuration simulator.

**Comment by ricktu288** [comment]
The "detector" is implemented with an estimation of the above error indicated.
