### ISSUE TITLE
Add Frensel lens

### ISSUE THREAD

**Issue by damien-ls** [ricktu288/ray-optics#21]
Would be great to have frensel lens capability

**Comment by vannomad** [comment]
Fresnel lenses are just normal lenses mathematically speaking, they just require a lot less material and lenses aren't displayed in this simulator anyways

**Comment by alhirzel** [comment]
It would make a really cool example lens!

**Comment by ricktu288** [comment]
Example added in #60 by @StasFainer.

However, a direct tool to create this (with tunable parameters) is still desired.

**Comment by ricktu288** [comment]
Now it can be created with Glass -> Custom equation
![image](https://user-images.githubusercontent.com/1409171/200151716-f22cc50f-2783-40c0-9d23-2525ebd04677.png)
