### ISSUE TITLE
Glass circle changes to a circle filled with different medium

### ISSUE THREAD

**Issue by DomBadger1992** [ricktu288/ray-optics#23]
I am working on a project where we need to know the glare points location on a soap bubble (soap skin but air inside the bubble). When the light sources are in different positions, the glare points are expected to show up in different places on the bubble. In the current application, I could only put a glass circle but the refractive index of the glass is not close to the refractive index of the air, therefore I am not able to obtain what I want. 
Could users set the medium of the glass circle, for example, make it an air circle.

**Comment by cincodenada** [comment]
This is probably way too late for your needs, but for others: you can change the index of refraction of any of the glass elements in the Settings portion of the toolbar.
