### ISSUE TITLE
Allow setting color of light sources

### ISSUE THREAD

**Issue by pbz** [ricktu288/ray-optics#25]
It would be very helpful in certain situations if it were possible to set the color of a light source (and therefore the representation of its rays), so that it is possible to discern rays from different sources once they start to overlap.

**Comment by shufflebits** [comment]
Coloured light sources would be useful.

Yi-Ting Tu, this is a very useful program! Thank you very much for making it. :-)

**Comment by ricktu288** [comment]
I have modified the structure of `obj`s to allow multiple input boxes/slider for parameters. Now it is easier to implement multiple colors (e.g. add a "color" input box for light sources.)
Note that there is also #32 that need the colors not for discerning sources but for aberration.

**Comment by ricktu288** [comment]
Implemented. Turn on "Simulator Colors" and you can set the colors by setting the wavelength of the sources.
