### ISSUE TITLE
How to force reset optical system to the default one

### ISSUE THREAD

**Issue by anandr** [ricktu288/ray-optics#28]
I accidentally increased ray density to some high value and now whenever I open https://ricktu288.github.io/ray-optics/simulator/ it freezes for some time without showing its interface (as I understand it tries to trace too many rays) and then that tab dies.
How to force reset ray density for light sources?
Or the whole optical system?

**Comment by pfalstad** [comment]
For now you can clear local storage: https://www.leadshook.com/help/how-to-clear-local-storage-in-google-chrome-browser/
