### ISSUE TITLE
Inaccurate sample file descriptions

### ISSUE THREAD

**Issue by Steuard** [ricktu288/ray-optics#29]
I'm interested in looking at samples of what this cool simulation can do. I quite like the "Images formed by two mirrors" example (I've sometimes assigned a similar exercise as a homework problem), and "Spherical lens and mirror" is lovely. But the other sample files provided don't seem to match their descriptions at all:

- "Apparent depth of an object under water" shows instead a few light sources outside of a convex mirror (and their images).
- "Compound microscope" shows instead the third sample image from the website (a refracting rectangle, a gradient, and a light ray bouncing between a flat and curved mirror), with an extra protractor thrown in.
- "Reflection and refraction of a single ray" shows instead a point source shining through a slit toward an ideal diverging lens.

Are these files the intended ones?

**Comment by ricktu288** [comment]
Fixed.
