### ISSUE TITLE
The ability to change the angle (orientation) of the object without changing the X and Y coordinates

### ISSUE THREAD

**Issue by mohammedsait** [ricktu288/ray-optics#31]
It is important to rotate an object to a certain angle without altering its x-y coordinate. changing the angle of the an object , e.g., say a source of ray beam, will change the width of the beam. therefore it is very important to have an option to enter the angle of orientation of the abject. 

Thanks

**Comment by TwoToneEddy** [comment]
I would also like this

**Comment by ricktu288** [comment]
For the beam, you can hold the Ctrl key while dragging its endpoints. It will rotate about its center (but the length may change nevertheless.)

**Comment by ricktu288** [comment]
1. Hold Ctrl, and click all the control points in the object (works also for part of an object or across several objects).
2. Click the empty space to create a handle.
3. Hold Ctrl and drag the handle to rotate the group of control points.
