### ISSUE TITLE
Possible chromatic aberration?

### ISSUE THREAD

**Issue by ashokavarthanan** [ricktu288/ray-optics#32]
Hi i am using this excellent.
when using **ideal lens** shows only ray changes.
can possible RBG chromatic aberration rays? 

https://en.wikipedia.org/wiki/Chromatic_aberration

thanks.

**Comment by ricktu288** [comment]
I have modified the structure of `obj`s to allow multiple input boxes/slider for parameters. Now it is easier to implement multiple colors (e.g. add a "wavelength" slider for light sources and a "dispersion" slider in glasses.)

**Comment by ashokavarthanan** [comment]
oh! thank you. long time ago.
add Examples?

**Comment by ricktu288** [comment]
Implemented.
Note that since the "Ideal lens" is ideal, it should not include chromatic aberration. Use a spherical lens instead.
