### ISSUE TITLE
add diffuser

### ISSUE THREAD

**Issue by NojmeS** [ricktu288/ray-optics#35]
Hi, can you please add a model for a diffusing surface?

**Comment by NojmeS** [comment]
One could calc the intersection of a ray and a point on the surface (where you calc snell) to split up the rays into subrays in a specific angle. Can you maybe point me to the location in the code to implement this by my own?

**Comment by ricktu288** [comment]
I have added instructions for "making your own tools" in README.md.

**Comment by NojmeS** [comment]
Thank you very much! :)

**Comment by ricktu288** [comment]
And a pull request is welcome after finishing the tool!

**Comment by DietToms** [comment]
@NojmeS @ricktu288 Hi there - I'm a microscopist interested in modelling illumination systems for educational purposes. I would be really interested in having this feature added or getting the code that was already made :)

**Comment by ricktu288** [comment]
See https://phydemo.app/ray-optics/gallery/specular-and-diffuse-reflection.
