### ISSUE TITLE
ruler and grid scales

### ISSUE THREAD

**Issue by Yibbou** [ricktu288/ray-optics#4]
Hi, very nice app,
Would it be possible to allow the user to configure the ruler and the grid scales. That is, the option to choose between centimeters (millimeters),  inches and pixels (if possible).

Best regards

**Comment by j3soon** [comment]
The new version now supports zooming. You can control the zoom percentage by scrolling your mouse wheel.

**Comment by ricktu288** [comment]
The unit is an arbitrary length scale. Whether it is cm or px is not important since all the lengths used in this app have the same unit.
