### ISSUE TITLE
请问是需要特殊的浏览器版本吗？

### ISSUE THREAD

**Issue by flystarhe** [ricktu288/ray-optics#44]
为什么我的浏览器打开，网页显示很奇怪
![网页捕获_22-5-2022_1511_](https://user-images.githubusercontent.com/5718508/169683080-a5688e76-2c97-4250-8a0b-ef5f173ef11d.jpeg)
？

**Comment by j3soon** [comment]
I thinks your issue is same as #40.

Can you post a screenshot of the console logs in the console window? (`Ctrl+Shift+I > Console`)

Did the error persist in Incognito/Private Mode?
