### ISSUE TITLE
Toolbar is not visible while uBlock is active

### ISSUE THREAD

**Issue by dorukcan** [ricktu288/ray-optics#45]
Due to a ad selector (`body > div[id="toolbar"][style]`) in uBlock Origin, the toolbar is not visible (displayed as none). I can only see the element `optionsbar`.

Browser: Chrome 102 on macOS.

**Comment by j3soon** [comment]
Can you provide a screenshot? I cannot reproduce your issue on Chrome 102 with uBlock Origin.
