### ISSUE TITLE
Is it possible to calculate radiation pressure with this simulator?

### ISSUE THREAD

**Issue by michaellee8** [ricktu288/ray-optics#5]

**Comment by ricktu288** [comment]
There is currently a power-measurement branch in this repo. It contains a tool for measuring the power through a surface, which can be converted to the radiation pressure.

However, that implementation has some serious issues (see the comment in #27), so I am not currently considering merging it to the main branch.

**Comment by ricktu288** [comment]
Implemented. An estimate of the error mentioned before is also indicated.
