### ISSUE TITLE
Wrong sign in Focal length parameter?

### ISSUE THREAD

**Issue by carlabarato** [ricktu288/ray-optics#50]
I see ray-optics simulator is using **image** focal length as parameter for ideal lens and ideal mirrors, but the name of the parameter is "focal length", not "**image** focal length".

This is confusing especially in ideal mirrors, since mirrors do not have "image focal points", just "focal points":
- a concave mirror has a negative focal length
- a convex mirror has a positive focal length
- see this example for a convex mirror: focal length should be +100, not -100: https://screenrec.com/share/yxwoefucJ9

Could you change the parameter sign for ideal lens and ideal mirrors?

**Comment by ricktu288** [comment]
I followed the sign convention of the General Physics textbook I used. I think it is also the sign convention used in most high schools and universities. For example:
https://www.physics.louisville.edu/cldavis/phys299/notes/lo_spmirror.html

**Comment by carlabarato** [comment]
I see your text book is using the right sign convention: https://screenrec.com/share/aWCF4QjkrJ
that is, a convex mirror has a positive focal length, but in simulator we see this negative: https://screenrec.com/share/yxwoefucJ9

**Comment by carlabarato** [comment]
In my text book, if rays come from left to right, distances are measured positive to the right of vertex, negative to the left (Spanish):
https://screenrec.com/share/J3bX4RSMGD

See this reference in English:
https://www.excellup.com/classten/scienceten/lightreflection4.aspx

And tthis video:
https://www.khanacademy.org/science/in-in-class10th-physics/in-in-10th-physics-light-reflection-refraction/in-in-sign-conventions/v/sign-conventions-for-mirror-lenses

**Comment by carlabarato** [comment]
In my text book, if rays come from left to right, distances are measured positive to the right of vertex, negative to the left (Spanish):
https://screenrec.com/share/J3bX4RSMGD

See this reference in English:
https://www.excellup.com/classten/scienceten/lightreflection4.aspx

And this video:
https://www.khanacademy.org/science/in-in-class10th-physics/in-in-10th-physics-light-reflection-refraction/in-in-sign-conventions/v/sign-conventions-for-mirror-lenses

Check video transcript (_"negative focal length automatically implies concave mirror, positive focal length implies convex..."_):
https://screenrec.com/share/iMSL9ebwIK

**Comment by ricktu288** [comment]
I added a checkbox for ideal curved mirror for the convention you mentioned (the Cartesian Sign Convention). For ideal lens, I think the Cartesian Sign Convention gives the same sign as the original convention, so no change is made.

This option is off by default, since most of the General Physics textbooks in use still follow the old convention (as far as I know). And at least in Taiwan, the high school education also uses the old convention (see the sentence below equation 4-2 on page 10 of https://moodle.fg.tp.edu.tw/~tfgcoocs/blog/wp-content/uploads/2015/10/%E9%AB%98%E4%B8%89%E7%89%A9%E7%90%864-2%E7%90%83%E9%9D%A2%E9%8F%A1%E8%AA%B2%E6%9C%AC_%E7%A9%BA%E7%99%BD.pdf).

If the new convention is the default in some country/region and the locale for that country/region is added, this option can be on by default for that locale.

**Comment by carlabarato** [comment]
I understand now, thanks for the explanation. I think this solution is perfect, thank you!

Have you considered the same solution for ideal lens? 
I've studied that a convergent lens has a negative focal length (or a positive **image** focal leght), whereas a divergent lens has a positive focal length (or a negative **image** focal leght)
https://screenrec.com/share/dRqZjfUxtl

**Comment by ricktu288** [comment]
I use Google Lens to translate the link, but I only see "image focal length", not "focal length". Is there a reference that defines the "focal length" as you mentioned?

**Comment by carlabarato** [comment]
you can find the definition of "focal length" and "image focal length" here: 
https://www.fisicalab.com/apartado/lentes-delgadas

again sorry for the Spanish, go to section "Focos"
https://screenrec.com/share/2UO8QRmade

**Comment by carlabarato** [comment]
I checked this at Wikipedia:
https://en.wikipedia.org/wiki/Focal_length#General_optical_systems

_"Back focal length or back focal distance is the distance from the vertex of the last optical surface of the system to the rear focal point (F′)."_

They use the term "back focal length", but I prefer "image focal length" because in divergent lens F' is at the front.

I think we can avoid sign convention misunderstanding just with your solution above?

**Comment by ricktu288** [comment]
Note that in the "thin lens approximation" section of that wiki article, it only uses "focal length", and the sign convention is the same as the simulator. I think the distinction you mentioned is only for thick lens, where the optical system is regarded at two separate surfaces having their own focal lengths.

Therefore, in this simulator, only the "Spherical lens" tool may have this concern, not the ideal (thin) lens. Currently, the only number-parameter for that tool is the refraction index, so nothing need to be changed for now.

On the other hand, if the Spanish education system always uses that term, even for thin lens, then the Spanish for "image focal length" should be used for the Spanish locale of the simulator (which does not exist yet. It would be a great idea to contribute a new locale by translating `index.html` and `simulator/locale/en.js`, then open a pull request.)

**Comment by carlabarato** [comment]
ok, understood
thank you!
