### ISSUE TITLE
wrong refraction index for glass on top

### ISSUE THREAD

**Issue by carlabarato** [ricktu288/ray-optics#51]
I set a half-plane with refractive index = 2.5, and then I put on top a free-shape with refractive index = 1.5
Then, inside the free-shape, the ray refracts as refractive index = 3.75 (not as 1.5)
I checked the effective refractive index is actually the product (3.75=2.5*1.5)

see screen shot: https://screenrec.com/share/PaJxQ45G6U

I think this is wrong because if I need the right refactive angle inside the top glass, in the case above, I have to set a refractive index of 1.5/3.75=0.6 (less than 1 should not be possible)

see screen shot: https://screenrec.com/share/4frvgjD3Bx

If I combine more than 2 glasses, one in top of the other, I checked the effective refractive index is the product of the top two.

**Comment by ricktu288** [comment]
Imagine you put a glass into water. You are not overlap the glass with the water, but are changing the shape of the water. If you submerge it into the water, the shape of the water becomes "a rectangle minus the shape of the glass". Therefore, the proper way to draw in this simulator is to first draw the "water" like this:
![圖片](https://user-images.githubusercontent.com/1409171/188271974-f2fb3ef8-7222-4c13-8c86-8fd035f8dc0a.png)
And then put a glass in the hole of the water.

Overlapping two glass objects should be considered as an undefined behavior of the simulator (we do not really overlap objects in real life). Currently, the actual behavior is that the refractive indices multiply in the overlapping region.

**Comment by ricktu288** [comment]
I think a more intuitive overlapping behavior is that the glass created later always replace the glass created first. But implementing that would be quite difficult. I think I will just add a notice to clarify the current behavior.

**Comment by carlabarato** [comment]
I get it. Maybe you can help me on this case?
I was trying to simulate this problem from my text book:
<img width="472" alt="EVAU 4B julio 2009_2010_coincidentes" src="https://user-images.githubusercontent.com/103997018/188282968-4594edec-4d6c-4016-b8bf-fee1417e8b06.png">

**Comment by carlabarato** [comment]
Find attached my simulations to answer a) and b). I made it using a half-plane. I see you are proposing a free-shape with a hole but I don't know how to do that?

simulation for a)
https://drive.google.com/file/d/13k9VBICYcUOVQ0tl1jlGPrYIzhW6ewEM

simulation for b)
https://drive.google.com/file/d/1m5zUL6EnIqZmDgFX3ICD-CGfBFw0DVkj

**Comment by ricktu288** [comment]
![圖片](https://user-images.githubusercontent.com/1409171/188515343-558ff726-c87b-4e51-be8a-64696479712f.png)

**Comment by carlabarato** [comment]
understood, thank you!
