### ISSUE TITLE
Group items in Examples

### ISSUE THREAD

**Issue by ricktu288** [ricktu288/ray-optics#54]
Currently, the "Examples" list is too long and not organized.

I suggest using nested lists within the example dropdown. The current examples can be organized as follows (contributor in the parenthesis):

**Reflection of light**
-  images-formed-by-two-mirrors.json (Yi-Ting Tu)
-  parabolic-mirror.json (Paul Falstad)
-  retroreflectors.json (Stas Fainer)
-  maze-solution.json (Stas Fainer)
-  optical-cavity.json (Stas Fainer)
-  penrose-unilluminable-room.json (Vincent Fan)

**Refraction of light**
-  reflect.json (despite the name, it is more related to refraction) (Paul Falstad)
-  internal-reflection.json (Paul Falstad)
-  prisms.json (Paul Falstad)
-  apparent-depth-of-an-object-under-water.json (Yi-Ting Tu)
-  chromatic-dispersion.json (Yi-Ting Tu)
-  bended-pencil.json (Stas Fainer)
-  broken-pencil.json (Stas Fainer)
-  inferior-mirage.json (Stas Fainer)
-  GRIN-slab.json (Stas Fainer)

**Lens**
-  concave-lens.json (Paul Falstad)
-  convex-lens.json (Paul Falstad)
-  lens-images.json (Paul Falstad)
-  monochromatic-aberrations.json (Stas Fainer)
-  luneburg-lens.json (Stas Fainer)
-  maxwell-fisheye-lens.json (Stas Fainer)
-  fresnel-lens.json (Stas Fainer)

**Combination of Lenses**
-  zoom-lens.json (Paul Falstad)
-  compound-microscope.json (Yi-Ting Tu)
-  rochester-cloak.json (Stas Fainer)
-  beam-expanders.json (Stas Fainer)
-  telescope.json (Stas Fainer)

**Miscellaneous**
-  reflection-and-refraction-of-a-single-ray.json (Yi-Ting Tu)
-  spherical-lens-and-mirror.json (Yi-Ting Tu)
-  NL-simulation.json (Kimmik)

And I think there may be a way to make the addition of new examples to the lists easy.

**Comment by Yibbou** [comment]
+1

Le jeu. 22 sept. 2022 à 02:35, Yi-Ting Tu ***@***.***> a
écrit :

**Comment by ricktu288** [comment]
Other possible designs:
1. Use a sidebar, instead of the dropdown, to show a nested list of the examples
2. Let the dropdown scrollable, and sort the items according to the groups, with a label added before each group.
3. make the dropdown multi-column, where each column represent one group.

**Comment by ricktu288** [comment]
I am planning to replace the Examples menu by a gallery webpage, so this is no longer necessary.
