### ISSUE TITLE
Density option for the ruler scale marks and the grid

### ISSUE THREAD

**Issue by StasFainer** [ricktu288/ray-optics#57]
It would be nice to enhance the ruler and grid tools, by adding the option to set the density of the scale marks and the grid itself (for now there’s only one default density for both).
This could be useful for making more accurate simulations (as I encountered when experimenting with different configurations).

**Comment by ricktu288** [comment]
For now, you can enhance the accuracy by double-clicking a control point and enter its coordinates (in pixels) manually. (Hover the "Help" button for more tips.)

**Comment by ricktu288** [comment]
@j3soon Is it straightforward to make the "Grid" a dropdown with options of different sizes (or a text box without slider)?

**Comment by StasFainer** [comment]
Cool!
Thanks for the tip :)

**Comment by ricktu288** [comment]
The "Grid Size" options is now available in Settings.
