### ISSUE TITLE
Implement Beam-Splitter

### ISSUE THREAD

**Issue by raumneun** [ricktu288/ray-optics#6]
First of all, Rick, thank you for this awesome tool. I use it quite often to get an impression of my laser beam paths and potential influences of drifts in beam position. For this, it would be nice to feature a beam splitter to see the influence of mirror dealignments at two (or more) different positions. 

The easiest (and probably most often used) would be an intensity beam-splitter with an adjustable transmission/reflection ratio. Other ideas would be to implement a polarization option to the light sources and add polarizing beam splitters. Thanks for giving this suggestion a thought!

**Comment by elias-scharf** [comment]
I also relay like your work Rick. Thanks!
To simulate a beam-splitter you can choose glasses - free shape. With this you can create a very thin quadrangle. Therefore it is useful to double click the corners and edit the coordinates of them. Than you can adjust the ratio by the refractive index. Its not very ease of handling but it works.

**Comment by siran** [comment]
Using a free-shaped glass is a workaround to simulate a beam splitter. But definitely less than ideal.
I discovered this tool days ago, and I find it really helpful!! THANK YOU, Rick!
+1 vote for Beam Splitter.

**Comment by ricktu288** [comment]
Implemented by pfalstad.
