### ISSUE TITLE
refractive index

### ISSUE THREAD

**Issue by pdm55** [ricktu288/ray-optics#7]
I cannot see how to set the refractive index. I wish to have a ray pass from air to glass, travel through the glass then pass back out into air. I would also like to pass a ray through a series of materials with different refractive indices. I just cannot see how to set up layers with different refractive indices. Perhaps you could show us with a short video?

**Comment by ricktu288** [comment]
Click the glass object (on its edge) and you will see a slider to adjust its refractive index.
