### ISSUE TITLE
New toolbar design?

### ISSUE THREAD

**Issue by ricktu288** [ricktu288/ray-optics#70]
During the past few years, several people have pointed out that the current toolbar layout may not be optimal, and some new designs have been proposed.

One is [this fork](https://github.com/krzysztofkrzeslak/ray-optics) by @krzysztofkrzeslak:
![image](https://user-images.githubusercontent.com/1409171/200175109-c320f1db-649b-45c7-a018-3352a33cd336.png)
![image](https://user-images.githubusercontent.com/1409171/200175167-816d1986-4590-4bb5-aab4-cfea568202f4.png)

Another is a [recent prototype](https://github.com/ricktu288/ray-optics/files/9946153/vincentfan1024.zip) by @vincentfan1024:
![image](https://user-images.githubusercontent.com/1409171/200175291-2820c1ec-8610-46aa-a785-b5f9ff49cf57.png)
![image](https://user-images.githubusercontent.com/1409171/200175323-a5724750-ec85-4c3c-bf1b-dfdcf9c6e41e.png)
(the placeholder icons are to be some visual representations of the tools/views)

Since people use this app in very different ways and on very different devices, it is difficult for us alone to find an optimal design. So I open this issue for discussion.

Feel free to share your thoughts and ideas in the comments below.

**Comment by krzysztofkrzeslak** [comment]
Hi, I really like a design from @vincentfan1024 clean and simple, need to check it though. Btw. nice that you're still developing this project!

**Comment by ricktu288** [comment]
I have added the link to the zip file of @vincentfan1024's design in the first comment.

My main concern on @vincentfan1024's design is that, since "grid" and "ray density" options will be in the "options" dropdown, it may cause some inconvenience for people who adjust/switch them very often. One solution is to add hotkeys (in older version, holding Alt overrides "snap to grid", but it seems not working properly currently.)

Also, for new users, I don't know how quickly they will find that "ray density" function exists, especially when they first try to create a point source or beam, and finding no options in the obj bar (parameter box) that can change the numbers of rays emitted.

**Comment by krzysztofkrzeslak** [comment]
If you like mine approach more I can sit on it a bit to make it more readable also, because I see some flaws in it also, but can agree that all function are visible right away so it can be a plus. I would add a small separator between tools/view and setting toolbar for example, as well some icons like @vincentfan1024 did so we could like merge two solutions.

**Comment by ricktu288** [comment]
Good idea, and thank you for the contribution.

**Comment by ricktu288** [comment]
Here are my thoughts. They may not reflect the average thoughts of users.

1. I like the transparent toolbar background more, since it allows the scene to be extended to the whole page, and it looks more nature for people using dark mode in browsers.
2. The tools and view buttons are better to be in blue than in gray, as they are more important than the options like grid. The latter are better to be in gray.
3. Tools can be grouped into Source/Blocker/Mirror/Glass/Measurement/Decoration (the last group currently only has "text"). "Move view" can just be an icon.
4. In addition to having just icons, the "view" can also be a single dropdown.
5. The "simulate colors" may either be grouped with "view" (as it is currently) or next to "ray density".
6. If there is no "welcome window" appearing when people first enter the app, then the "Examples" should be visible in the toolbar (also see #54).
7. On small screens, I think it is possible to set several toolbar layouts in the current knockout framework, so that the buttons are automatically changed (like just icons or similar to @vincentfan1024's design)?
9. I think the log number text box of "ray density" is weird.
8. I think people almost always turn "grid" and "snap to grid" on/off together. It may be simpler to merge into one button with dropdown options (also see #57).
10. I like the floating object bar in @krzysztofkrzeslak's design. Note that some recently added tools have several options that may cause wrapping.

**Comment by ricktu288** [comment]
@vincentfan1024 also sent me a handwritten draft for possible icon design.

![image](https://user-images.githubusercontent.com/1409171/200329014-4248331c-54c8-4a8b-bbf0-0034b1022787.png)

I think the icons for views and options can be used. For the tools, however, I prefer just use text with screenshot images in the popover (as it is currently). My logic is that since the appearances in the simulator itself are already visual representations of real physical objects, it is a little bit weird to have another visual representations of the visual representations in the toolbar.

**Comment by ricktu288** [comment]
Here is the updated prototype/mockup that combines both designs and attempts to resolve the concerns above.
[prototype.zip](https://github.com/ricktu288/ray-optics/files/12326222/prototype.zip)
![prototype](https://github.com/ricktu288/ray-optics/assets/1409171/d5bb0890-7403-4875-a015-d8d7d8674581)
Note that I haven't thought about the dropdowns/popover/tooltips yet.

If this is to be implemented, then both @vincentfan1024 and @krzysztofkrzeslak will be listed as contributors to the UI design.

The current plan is to implement this with Vue.js and replace the current knockout.js framework.
Feel free to make comments or suggestions.
