### ISSUE TITLE
Who to open a local .json file

### ISSUE THREAD

**Issue by Archiballe** [ricktu288/ray-optics#78]
Hello, 

When I open a .json file, the graphic area remains black and I cannot interact. 
I specify that .json has been downloaded with the save function 

Can anyone help me? 

Thx

**Comment by ricktu288** [comment]
Can you attach the .json file (or send me) so that I can check what is wrong?

**Comment by Archiballe** [comment]
[lentille.txt](https://github.com/ricktu288/ray-optics/files/10292067/lentille.txt)

(i have rename .json to .txt for easyer share)

**Comment by ricktu288** [comment]
Does adding back the comma solve your problem?

**Comment by ricktu288** [comment]
BTW, to modify the coordinates of a point, you don't need to edit the JSON. Just right-click or double-click on the point, then you can enter the coordinates.
