### ISSUE TITLE
Moving glass circle, some other stuff

### ISSUE THREAD

**Issue by Kjos** [ricktu288/ray-optics#8]
I'm loving this application. Very convenient and very well done.
I have a few comments, most of which minor:
- x Creating a glass circle and then moving it, resizes the circle to the origin point. It would be better if the circle doesn't resize at all. It may be that I am unaware of a key combo?
Edit: I see now that the circle has two dots. I didn't see the dark purple dot at first.
Edit: Grabbing the edge of things moves them. That makes sense.
- I am missing a feature that allows to pass the ray through a filter (for example rainbow), so you can keep better track of how the rays flow. This would benefit me greatly.
- Not really bothersome, but the save function is missing an extension
- Some small text at the bottom with the coordinates of the selected item. You can use the ruler now, but it just seems some coordinates (and mouse coordinates) could be more convenient.
- x I am unable to move a custom shaped lens. I was expecting a point in the middle to drag it.
- Overall the UI could need some work. Or a bit more extensive manual would already help a great deal for new users.

Overall, this is awesome. Hats off.

**Comment by ricktu288** [comment]
HI,
- For glasses (circle or other shapes), you can move them as a whole by grabbing the edge of the glass, not on the dots.
- This application currently simulates only monochromatic light, so there is no way to create rainbows, but you can change the refractive index to different values to see how the deflection angle changes.
- You can right-click or double-click on a dot to view or set its coordinates.
Sorry for no enough guides on how to use this app.

**Comment by Kjos** [comment]
Thanks for those tips ricktu and thanks for your hard work on this. Have a good end of 2017 and start of 2018.
