### ISSUE TITLE
The Color Space is Inaccurate 

### ISSUE THREAD

**Issue by gljames24** [ricktu288/ray-optics#81]
Based on the CIE 1931 color space, the colors used in this application are off.
Blue should be 460nm, but it is at 440nm currently
Cyan: 500, 490
Green: 540,  510
Yellow: 580, 580
Red: 620, 650
These colors were captured using Gnome Color Picker using the HSV color space in the application to verify the color. 
Overall, the hue range in this application is larger than how human perception would see them. The color of yellow is accurate and cyan is close, but the range between yellow and green is overly large and the range between green and cyan is too narrow. As you can see, each real wavelength is 40nm away from each other which should result in the angle between each of these colors should be the same and the rays should to be equidistant, but as you can see [here](https://imgur.com/22Q5Bbo.png), that is not the case.

**Comment by ricktu288** [comment]
The wavelength-to-rgb in this app is based on this
https://www.scienceprimer.com/javascript-code-convert-light-wavelength-color

**Comment by gljames24** [comment]
Oh that's literally just an hsv mapping and the color constants are what I found. Except for red, but I had assumed they were multiples of 10. The literals just need to be fixed to what I had mentioned:
440 -> 460
490 -> 500
510 -> 540
645 -> 620
Also these should be constants instead of literals
