### ISSUE TITLE
Add Dichroic Glass Feature

### ISSUE THREAD

**Issue by gljames24** [ricktu288/ray-optics#82]
A dichroic glass acts like a mirror to a specific frequency range while acting like a normal piece of glass for all other other frequencies. This is often used in expensive cameras and projectors. In these devices they split and combine color channel to produce a full composite image of a higher fidelity. This in contrast to using subpixels. The addition of dichroic glass would make designing these devices easier.

**Comment by gljames24** [comment]
I thought about this some more. I was thinking that it could work as a selectable range on the mirror objects when simulate colors is active. Essentially, a ray would only reflect if it's wavelength is within the mirror's range; otherwise, it would act as if the mirror didn't even exist. I'll look over the code some more to see if I could implement this myself.

**Comment by gljames24** [comment]
I got it working:
![image](https://user-images.githubusercontent.com/22029083/214202513-d54d8dec-2b48-4da9-bd10-56d6d92ef2f7.png)

**Comment by gljames24** [comment]
The only thing I really have left to do is implement the toggle for the feature. I decided to let the mirror only reflect a specific wavelength rather than use a range of values as that would be difficult to implement.

**Comment by gljames24** [comment]
I noticed thru testing this that the beam / parallel obj brightness doesn't work properly and and the as it only mixes color up to 0.1 instead of 1. So, I might open that up as a seperate issue.

**Comment by gljames24** [comment]
Submitted a pull request for the feature enhancement #87

**Comment by gljames24** [comment]
I fixed an issue with the toggle I had made so I'll have to commit that.
But I also wanted to add this feature to all of the mirrors, so I am working on that. 
I'll also get that example in.

**Comment by ricktu288** [comment]
https://en.wikipedia.org/wiki/Dichroic_filter
Is it more common for a dichroic filter to pass a specific color only than to reflect a specific color only?

**Comment by gljames24** [comment]
So they have a passband and a stopband. I couldn't think of a good way to allow the user to input a range of values. I looked at sliders, but that means adding a whole jquery thing. We could use two number inputs, but I thought that was clunky looking. It would work as you could keep track of which one is higher and replace the x != y to y¹ < x < y² to determine if the light reflects or passes thru. 
I also thought that this would work the same way as the light sources as they need multiple light sources to have multiple wavelengths. Adding wavelength ranges to objs could be its own issue, or we can try to figure it out just for the dichroic feature.

**Comment by gljames24** [comment]
I got all the mirrors done and added the example here in #89.

> https://en.wikipedia.org/wiki/Dichroic_filter Is it more common for a dichroic filter to pass a specific color only than to reflect a specific color only?

I misread this comment. Do you want to add a toggle between reflecting all but one wavelength and only reflecting one wavelength?

**Comment by ricktu288** [comment]
I think that is a good idea.

**Comment by ricktu288** [comment]
![image](https://user-images.githubusercontent.com/1409171/214667437-75f47759-82d8-4ec5-9d5f-f2a564422341.png)
Another issue happens when use the dichroic mirror as a coating of a glass. The ray will not refract.

I think one way to solve this is to return nothing in `rayIntersection` if the ray is not to be reflected.

**Comment by gljames24** [comment]
I'll work on that and the other toggle.

**Comment by gljames24** [comment]
So I altered the shot function in mirror obj to create the reflection ray when it should be reflected and otherwise the ray passed to the function will not be given a p1 or p2, but that causes an error as it is expecting a ray as seen here: 
![image](https://user-images.githubusercontent.com/22029083/214691027-b2712f9d-2ace-4f98-9cb0-c57fe3bba025.png)

Looking at rayIntersection, that probably seems like the better way to do it. I will move the reflection code back into shot and will need to spend some time looking into how best to implement it. I think I might want to override the parent class, check if the surface is reflective and then call the super class's rayIntersection method.

**Comment by gljames24** [comment]
I got it working. I'll implement it for all other mirrors and add the word "filter" to the language definitions. That should close this issue.
![image](https://user-images.githubusercontent.com/22029083/214741036-3ea37560-171e-4018-bca6-9f7a6fd71d53.png)

**Comment by gljames24** [comment]
Unless there are any further issues or changes you want to make, #90 should be able to close this issue.

**Comment by ricktu288** [comment]
https://phydemo.app/ray-optics/gallery/dichroic-rbg-splitter-and-combiner
This example is broken after your last pull request.

**Comment by ricktu288** [comment]
Also, when the user first clicks the checkbox, the dichroic feature is not turned on until the user drags the slider.

**Comment by gljames24** [comment]
> https://phydemo.app/ray-optics/gallery/dichroic-rbg-splitter-and-combiner This example is broken after your last pull request.

That is due to the dichroic boolean being changed to isDichroic when I added the isDichroicFilter boolean. I can send you the updated json file for that along with an LCD pixel example for the filter property of the dichroic glass feature.

> Also, when the user first clicks the checkbox, the dichroic feature is not turned on until the user drags the slider.

I can add it to set the color to green by default or the wavelegth value when they turn the dichroic feature on. I didn't realize that I had already taken care of the problem I had before where setting the wavelength value would override the dichroic setting.

I'll just change all the intances of:
<obj.wavelength = obj.isDichroic? value : NaN;>
into
<obj.wavelength = value;>
and then send a quick pull request.

**Comment by gljames24** [comment]
I fixed the issue in #91 and sent the updated and new example to "ray-optics@phydemo.app."
